version: '3'

services:
  client:
    build:
      context: ./client
      args:
        - VC_SERVER_URL=http://stg-signal.vitalchat.com:1080
        - API_SERVER_URL=http://localhost:3000
    ports:
      - 3001:80

  server:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - VC_SERVER_URL=http://stg-signal.vitalchat.com:1080
      - VC_KEY=test
      - VC_SECRET=dfff6d37-4a7f-4d4d-9d48-14b6e8958ecb
      - WATSON_URL=https://gateway-tok.watsonplatform.net/assistant/api
      - WATSON_ASSISTANT_ID=ffad920c-9d37-4522-812a-35777b57cc27
      - WATSON_IAM_APIKEY=LpRgQnxxROitLdRAW0dJS1tuBj7evM4coxj94Jz1PWp8
