version: '3'

services:
  client:
    build: ./client
    ports:
      - 9000:80
    environment:
      - API_SERVER_URL=https://demo.vitalchat.com

  server:
    build: ./server
    ports:
      - 9001:9001
    environment:
      - VC_SERVER_URL=https://stg-signal.vitalchat.com
      - VC_KEY=af561773-acf3-4d8d-9574-79d847e50734
      - VC_SECRET=2eaed0bd-8327-417c-8088-02093b1a696e
